config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :projects do
    resources :tasks, except: [:index], controller: 'projects/tasks'
  end

  root "projects#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates_presence_of :title
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects/tasks_controller.rb
class Projects::TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project, only: [:show, :new, :edit, :create, :update, :destroy]

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
      @task = Task.new(task_params)
      @task.project_id = @project.id

      # respond_to do |format|
        if @task.save
          redirect_to '/projects'
          # format.html { redirect_to project_path(@task.project_id), notice: 'Task was successfully created.' }
          # format.json { render :show, status: :created, location: @task }
        else
          format.html { render :new }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        # end
      end
    end

    def update
    respond_to do |format|
      if @task.update(task_params)
        redirect_to '/projects'
        # format.html { redirect_to action: "index", notice: 'Task was successfully updated.' }
        # format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

    def destroy
      @task.destroy
      redirect_to '/projects'
      # respond_to do |format|
      #   format.html { redirect_to project_url(@task.project_id), notice: 'Task was successfully deleted.' }
      #   format.json { head :no_content }
      # end
    end

    private
      def set_task
        @task = Task.find(params[:id])
      end

      def set_project
        @project = Project.find(params[:project_id])
      end

      def task_params
        params.require(:task).permit(:title, :project_id)
      end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    # respond_to do |format|
      if @project.save
        redirect_to '/projects'
        # format.html { redirect_to @project, notice: 'Project was successfully created.' }
        # format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      # end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/projects">listy.online</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"></li>
        <!-- <li></li> -->

      </ul>
      <form class="navbar-form navbar-left">


      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="about">About</a></li>
        <%= render 'devise/menu/registration_items' %>
        <%= render 'devise/menu/login_items' %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListyOnline</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  </head>

  <body>
  <%= render "layouts/header" %>

  <%= notice %>
  <%= alert %>

    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<br>
<% if user_signed_in? %>
<%= link_to 'New Project', new_project_path %>

    <div class="flex-container">
    <% @projects.each do |project| %>
      <div class="flex-item">
        <h1 class><%= project.title %></h1>
        <!--
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        -->
        <div class="alignright">
        <%= link_to 'X', project, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>

        </li>

          <% project.tasks.each do |task| %>
           <div class="flex-item2">
           <%= task.title %>

            <div class="alignright">
            <%= link_to 'X', [project, task], method: :delete %>
            </div>
           </div>

          <% end %>

          <div class="p">
          <%= link_to 'New Task', new_project_task_path(project) %>


          </div>
          </div>


    <% end %>
 </div>

<br>
<% else %>
Sign up/Sign in to start a new project
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<% @project.tasks.each do |task| %>
      Title: <%= task.title %>
      <% end %>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>
<%= link_to 'New Task', new_project_task_path(@project) %>

app/views/projects/tasks/_form.html.erb
<%= form_for [@project, @task] do |f| %>
      <% if @task.errors.any? %>
        <%= pluralize(@task.errors.count, “error”) %> prohibited this project from being saved:

        <% @task.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <!--<%= f.label :project_id %>
  <%= f.text_field :project_id %> -->
  <%= f.submit %>
<% end %>

app/views/projects/tasks/edit.html.erb
<h1>Edit a task</h1>
<%= render 'form' %>

app/views/projects/tasks/new.html.erb
<h1>Create a new task</h1>

<%= render 'form' %>

app/views/projects/tasks/show.html.erb
<%= @task.title %>